-- Seed data for blogs and quotes
begin;

insert into public.blogs (slug, title, excerpt, content, author, date, category, tags, image, featured, is_published) values ('tentang-kita-yang-tumbuh-dan-kalah-oleh-jarak', 'Tentang Kita Yang Tumbuh dan Kalah Oleh Jarak', 'Kadang, yang merusak bukan hanya jarak yang jauh, tapi ego yang tak mau saling mendekat.', '8 Oktober 2025. Masih kuingat pertama kali melihatmu saat itu. Kita tidak pernah benar-benar dekat, kita hanya saling menyukai dalam diam, sama sama malu mengungkapkan, sama-sama bingung harus melangkah kemana. Meski selalu merasa canggung, dan entah bagaimana. kamu tetap memilihku.

Setiap hari yang kita lalui, semuanya sangat menyenangkan, meski kita masih malu malu disaat itu, tapi hari hari itu benar benar menyenangkan. setiap langkah yang kita jalani menciptakan cerita yang indah. 

Setelah lulus, ku memutuskan melanjutkan sekolah dikota yang jauh. Meski terpisah oleh jarak, tidak ada alasan untuk mengakhiri semuanya, setiap waktu aku selalu menyempatkan pulang ke tempat yang sudah ku anggap rumah. Meski singkat kita bersenang senang bersama, tertawa bersama, dan menghabiskan waktu seolah kota kecil itu masih menjadi tempat kita berbagi mimpi.

Tapi perlahan semuanya berubah. Setiap badai datang, aku selalu bertahan untuk melindungi ego ku yang rapuh. Awalnya aku bisa bertahan, aku selalu mencoba memahami dirimu. Namun seiring waktu, lelah memelukku. Bukan karena cinta menghilang, tetapi karena aku merasa lelah menghadapi badai yang terus datang tanpa jeda.

Hingga akhirnya, aku memutuskan hubungan itu. Sejak hari itu, tidak pernah ku kembali ke tempat itu. Bukan karena tidak rindu, tapi karena sudah tidak punya alasan untuk pulang. Kamu pernah bilang bahwa kamu tidak merasakan cinta dariku, dan kata kata itu membuatku merasa semua perjuanganku sia sia. Sejak itu, aku kehilangan keberanian untuk kembali dan memperbaiki semuanya.

 Rasa sayang ini masih ada. Masih menyimpan banyak rasa yang tidak pernah benar benar hilang. Namun ketika kamu memintaku kembali, aku tidak bisa. Bukan karena tidak ingin, tapi karena takut membuatmu kecewa lagi. Takut kamu kembali merasakan hal yang sama, bahwa cintaku tidak cukup untukmu.

Karena itulah, pergi adalah pilihan. Bukan karena sudah tidak peduli, tetapi karena ingin kamu menemukan seseorang yang bisa membuatmu jauh lebih bahagia daripada sebelumnya. Seseorang yang bisa memberikan cinta dengan cara yang kamu butuhkan, seseorang yang bisa membuatmu merasa layak dicintai.', 'Qyuuu', '2024-11-29', 'Life', ARRAY['life'], '/image/blogImage/tentang-kita-yang-tumbuh-dan-kalah-oleh-jarak.jpg', true, true);
insert into public.blogs (slug, title, excerpt, content, author, date, category, tags, image, featured, is_published) values ('Merelakannya', 'Merelakannya?', 'Kadang cinta memang tak selalu tentang memiliki, tapi tentang melepaskan dengan ikhlas.', '30 November 2025. Merelakan seseorang yang kamu cintai, adalah proses panjang yang perlahan mengikis bahagia dalam dirimu. bukan karena cintamu kurang kuat, tapi karena semesta seolah tak pernah berpihak. kamu mencintainya sepenuh hati, kamu pernah berdoa dengan air mata yang jatuh diam-diam di malam hari, kamu pernah berharap setiap harinya hanya tentang dia, tapi pada akhirnya kamu harus sadar, bahwa tidak semua rasa layak diperjuangkan sampai habis-habisan. kamu mulai belajar menerima, walau hatimu menolak. kamu mulai berjalan menjauh, walau jiwamu ingin tetap tinggal. kamu mulai belajar tersenyum, di tengah luka yang tak pernah bisa kamu sembuhkan sendiri. setiap hari kamu berpura-pura tidak apa-apa, walau di dalam kepalamu namanya masih berisik, suaranya masih terngiang, senyumnya masih kamu ingat dengan jelas. kamu mencoba menghapus kenangan, tapi kenangan tak bisa kamu buang begitu saja. kamu mencoba mencintai orang lain, tapi tak ada yang mampu menggantikan tempatnya. kamu mencoba membenci, tapi hatimu tetap lembut jika bicara tentang dia. dan di antara semua itu, kamu tetap mencintai dalam diam, dalam jarak, dalam rindu yang tak bisa kamu tunjukkan. kamu belajar mengikhlaskan tanpa menghapus rasa, belajar menerima tanpa benar-benar rela, dan belajar berjalan sendiri tanpa arah yang jelas. dan mungkin inilah bentuk paling sunyi dari cinta, ketika kamu harus melepaskan seseorang yang kamu tahu, adalah satu-satunya yang ingin kamu genggam selamanya. kamu tetap berdoa agar dia bahagia, walau bukan denganmu. kamu tetap berharap dia baik-baik saja, meski kamu sendiri tidak pernah benar-benar baik semenjak kehilangan dia. dan akhirnya, kamu sadar, bahwa cinta bukan selalu soal memiliki, tapi soal keberanian untuk melepaskan, saat tetap bersamanya hanya membuatmu terluka lebih dalam setiap harinya', 'Phion', '2024-11-20', 'Life', ARRAY['life'], '/image/blogImage/tentangmu-yang-tak-pernah-bisa-ku-miliki.jpg', true, true);
insert into public.blogs (slug, title, excerpt, content, author, date, category, tags, image, featured, is_published) values ('dia-dan-mahkotanya', 'Dia dan mahkotanya', 'Dia, Mahkotanya dan bunga mawar di tangannya.', '04 Desember 2025. Aku bertemu dengannya, dia yang sempurna diantara yang lainnya, dia membawa bunga mawar di tangannya. mahkotanya yang indah membuatnya terlihat istimewa, tak sanggup aku memandanginya, bagaikan ratu berjalan diantara para kesatria yang siap melindunginya, aku salah satunya tapi bukan yang dia mau. Mungkin mengaguminya sudah lebih dari cukup, tidak harus lebih dari itu, sekedar kata saja tidak berani terucap dari mulut, bagaimana hati akan mengungkapkannya?', 'Phion', '2025-12-04', 'Life', ARRAY['life'], '/image/blogImage/dia-dan-mahkotanya.jpg', true, true);
insert into public.blogs (slug, title, excerpt, content, author, date, category, tags, image, featured, is_published) values ('teman-atau-harapan', 'Teman atau harapan?', 'Teman sebagai tempat cerita, atau harapan yang palsu?', '01 November 2025.', 'Phion', '2025-11-01', 'Life', ARRAY['life'], '/image/blogImage/teman-atau-harapan.jpg', true, true);
insert into public.blogs (slug, title, excerpt, content, author, date, category, tags, image, featured, is_published) values ('natal-api-kecil-2026', 'Natal, Api Kecil 2026', 'Malam yang dingin, api kecil yang selalu digenggam erat.', '23 Desember 2025. Kota ini terasa dingin, jendela kamar menghembuskan angin sejuk, jam di dinding menuntun jalan pulang yang tiada wujudnya. Dingin melilit jiwa, sepi menumpang di bahu layaknya sahabat lama yang tak kunjung pamit.

Cerita di tahun ini telah selesai, tidak ada lembaran yang menarik yang layak di ceritakan, setiap lembaran yang ada layaknya lembaran kosong yang hanya berisi tanda titik dan koma. Namun dari itu semua, di akhir cerita ini. kehangatan mulai muncul dari diri yang menghangatkan jiwa.

Dari rasa yang hilang, mimpi yang perlu di raih, tujuan yang perlu di perjuangkan, harapan yang tidak perlu di harapkan lagi, waktu yang tidak perlu di bagi, kesalahan yang tidak perlu diulangi kembali, keburukan yang di singkirkan, jalan yang perlu di pilih, dan masalah yang perlu di selesaikan. semua memeluk menciptakan rasa hangat yang perlu dipertahankan. 

Namun tetap saja dialiri rasa sepi yang mengalir pelan layaknya salju yang jatuh dari langit. Di sela hati dan fikiran yang berat itu, kehangatan yang ada dari api kecil itu dibesarkan diam diam, menelan perasaan dan kenangan yang memberatkan jiwa, mengusir kebiasaan buruk yang dulu dipelihara tanpa sadar yang mungkin menyakiti orang lain maupun diri.

2026 mengetuk pintu yang belum tergenggam utuh. Mimpi yang diikat di meja belajar akan diajak berlari mengelilingi dunia, tujuan yang ditulis akan diraih. Jika cinta hadir, biarlah hadir sebagai kompas yang menunjuk ke depan, bukan jangkar yang menarik ke belakang. Tahun baru ini tetap terasa sunyi, kepala menoleh lalu melihat diri sendiri, diri yang tetap berjalan dengan api kecil di dada, cukup untuk menyibak kabut yang mengahalangi pandangan dan harapan, cukup untuk percaya di halaman berikutnya bakal lebih ramai meski malam ini masih terasa asing dan sepi.', 'Phion', '2025-12-23', 'Life', ARRAY['life'], '/image/blogImage/natal-api-kecil-2026.jpg', true, true);

insert into public.quotes (date, text, author) values ('2026-01-12', 'Keknya jangan terlalu excited deh.', 'Phion Rushandle');
insert into public.quotes (date, text, author) values ('2026-01-10', 'Terlalu excited dan terlalu berharap itu gabaik, Jadi mulailah menganggap semua hal itu biasa aja.', 'Phion Rushandle');
insert into public.quotes (date, text, author) values ('2026-01-10', 'Keknya gaada chance sama sekali.', 'Phion Rushandle');
insert into public.quotes (date, text, author) values ('2026-01-01', 'Ga sedih, cuma perlu waktu buat nerima aja.', 'Phion Rushandle');
insert into public.quotes (date, text, author) values ('2025-12-28', 'Jika aku bertanya apa alasanmu mencintainya, bagaimana caramu menjawabnya?', 'Phion Rushandle');
insert into public.quotes (date, text, author) values ('2025-12-27', 'Aku mundur bukan karena tak berani, tapi karena aku tau cermin tak pernah berbohong.', 'Phion Rushandle');
insert into public.quotes (date, text, author) values ('2025-12-26', 'Segelas waktu untukmu. habiskan, aku akan mengambilkannya lagi untukmu esok hari.', 'Phion Rushandle');
insert into public.quotes (date, text, author) values ('2025-12-25', 'Seseorang bertanya kepadaku. "Kamu selalu ada untuk semua orang, tetapi ketika kamu butuh seseorang, siapa yang ada untukmu?".', 'Phion Rushandle');

commit;
